// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	EventID       int64              `json:"event_id"`
	Tickets       int32              `json:"tickets"`
	TotalPrice    pgtype.Numeric     `json:"total_price"`
	BookingStatus pgtype.Text        `json:"booking_status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	Location         pgtype.Text        `json:"location"`
	TicketPrice      pgtype.Numeric     `json:"ticket_price"`
	TotalTickets     int32              `json:"total_tickets"`
	TicketsAvailable int32              `json:"tickets_available"`
	Status           pgtype.Text        `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EventImage       pgtype.Text        `json:"event_image"`
	UpdatedAt        pgtype.Timestamp   `json:"updated_at"`
}

type Payment struct {
	ID             int64              `json:"id"`
	BookingID      int64              `json:"booking_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
	PaymentStatus  pgtype.Text        `json:"payment_status"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	Role              pgtype.Text        `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PasswordChangedAt pgtype.Timestamp   `json:"password_changed_at"`
}
