// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id int64) error
	GetBooking(ctx context.Context, id int64) (Booking, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetEventForUpdate(ctx context.Context, id int64) (Event, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListBooking(ctx context.Context, arg ListBookingParams) ([]Booking, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
